### ISSUE TITLE
Incompatibility issue with "Lock View" module

### ISSUE THREAD

**Issue by reubzilla** [shemetz/ZoomPanOptions#31]
Lock View module doesn't work when ZoomPanOptions is installed.

**Comment by Portacustos1** [comment]
have reproduced this issue, is there any chance of fixing this as one of our players is new from from roll20 really likes to moan a lot, and it would save us a lot of headaches lol

**Comment by itamarcu** [comment]
Issue on LockView's Github: https://github.com/CDeenen/LockView/issues/46

I believe I can try to solve the incompatibility, but I'll wait until after LockView updates to Foundry v9, as some breaking changes might have happened.

**Comment by Portacustos1** [comment]
hey :)

My player keeps asking me if this is fixed yet, I noticed LockView was updated, I don't know if you ever had a chance to look back at this?

**Comment by jocolamarco** [comment]
+1

**Comment by shemetz** [comment]
I'm still waiting for LockView to use LibWrapper as a dependency, but since a long time has passed without it happening, I decided to add a workaround in my own module that should fix the problem for most users.

Now, if ZoomPanOptions detects this conflict, it will attempt to resolve it by disabling zoom/pan for non-GM users as long as the scene flag 'lockZoom'/'lockPan' is set to true.

Added this in ZoomPanOptions v1.8.4.

Please let me know if this fixes the problems!

**Comment by CyricPL** [comment]
> I'm still waiting for LockView to use LibWrapper as a dependency, but since a long time has passed without it happening, I decided to add a workaround in my own module that should fix the problem for most users.
> 
> Now, if ZoomPanOptions detects this conflict, it will attempt to resolve it by disabling zoom/pan for non-GM users as long as the scene flag 'lockZoom'/'lockPan' is set to true.
> 
> Added this in ZoomPanOptions v1.8.4.
> 
> Please let me know if this fixes the problems!

It appears that the two are working correctly based on my initial testing. I still get the compatibility warning message, but that's to be expected. Thanks!

**Comment by jacksands** [comment]
thanks, just see this solution at lock view issues!

really tks for the effort
